## Churn Prediction

In [1]:
import keras

Using TensorFlow backend.


In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [31]:
dataset=pd.read_csv('new churn.txt')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [32]:
X=dataset.iloc[:,3:13]
Y=dataset.iloc[:,13]

In [33]:
Y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [34]:
geography=pd.get_dummies(X['Geography'],drop_first=True)
gender=pd.get_dummies(X['Gender'],drop_first=True)

In [37]:
gender.head()

Male
0     0
1     0
2     0
3     0
4     0

In [38]:
X=pd.concat([X,geography,gender],axis=1)

In [39]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0          1               1        101348.88        0      0     0  
1          0               1        112542.58        0      1     0  
2          1               0        113931.57        0      0     0  
3          0               0         93826.63        0      0     0  
4          1               1         79084.10        0      1     0

In [40]:
XX=X.copy()

In [41]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0          1               1        101348.88        0      0     0  
1          0               1        112542.58        0      1     0  
2          1               0        113931.57        0      0     0  
3          0               0         93826.63        0      0     0  
4          1               1         79084.10        0      1     0

In [42]:
X.drop(['Geography','Gender'],axis=1,inplace=True)

In [43]:
X

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
7706          667   31       5       0.00              2          1   
7707          848   35       5  120046.74              2          1   
7708          486   39       8   97819.36              1          0   
7709          598   64       1   62979.93              1          1   
7710          506   40       3       0.00              1          1   

      IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0                  1        101348.88        0      0     0  
1                  1        112542.58        0      1     0  
2                  0        113931.57        0      0     0  
3                  0         93826.63        0      0     0  
4                  1         79084.10        0      1     0  
...              ...              ...      ...    ...   ...  
7706               1         20346.69        0      1     1  
7707               0         84710.65        0      1     1  
7708               1        120531.31        0      0     0  
7709               1        152273.57        0      1     0  
7710               1        144345.58        0      0     0  

[7711 rows x 11 columns]

In [44]:
X.Male.value_counts()

1    4177
0    3534
Name: Male, dtype: int64

In [45]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [47]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [54]:
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [55]:
x_train

array([[ 0.34009365,  1.8068514 , -1.40342874, ..., -0.57360606,
        -0.57310682, -1.08180525],
       [ 0.89031623,  0.1945012 ,  0.68059705, ..., -0.57360606,
        -0.57310682,  0.9243808 ],
       [-1.64278394, -1.89206965, -1.05609111, ...,  1.74335674,
        -0.57310682,  0.9243808 ],
       ...,
       [-1.54934992,  1.61716314, -1.40342874, ..., -0.57360606,
        -0.57310682,  0.9243808 ],
       [ 1.71045931, -0.7539401 , -1.40342874, ..., -0.57360606,
        -0.57310682,  0.9243808 ],
       [-0.27241828,  0.8584101 , -1.40342874, ...,  1.74335674,
        -0.57310682, -1.08180525]])

In [56]:
x_test

array([[ 0.44902031, -0.37112512,  0.02940601, ..., -0.57460631,
        -0.59955931,  0.90175439],
       [ 2.00146847,  0.11764755,  0.02940601, ..., -0.57460631,
        -0.59955931, -1.10894941],
       [-1.03240081,  1.29070194, -1.35604367, ..., -0.57460631,
        -0.59955931,  0.90175439],
       ...,
       [-0.00758209, -0.07786152, -1.35604367, ..., -0.57460631,
         1.66789171, -1.10894941],
       [ 1.99132175, -1.15316138, -1.7024061 , ..., -0.57460631,
        -0.59955931,  0.90175439],
       [-1.01210737,  0.31315661,  0.72213086, ..., -0.57460631,
         1.66789171,  0.90175439]])

In [57]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU,PReLU,ELU
from keras.layers import Dropout

In [77]:
cl=Sequential()

In [78]:
cl.add(Dense(units=6,kernel_initializer='he_uniform',activation='relu',input_dim=11))

In [79]:
cl.add(Dense(units=6,kernel_initializer='he_uniform',activation='relu'))

In [83]:
cl.add(Dense(units=1,kernel_initializer='glorot_uniform',activation='sigmoid'))

In [85]:
cl.compile(optimizer='Adamax',loss='binary_crossentropy',metrics=['accuracy'])

In [87]:
cl.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_11 (Dense)             (None, 6)                 72        
_________________________________________________________________
dense_12 (Dense)             (None, 6)                 42        
_________________________________________________________________
dense_14 (Dense)             (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [88]:
m_hist=cl.fit(x_train,y_train,validation_split=0.33,batch_size=10,nb_epoch=70)

C:\Users\lenovo\.conda\envs\new\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Train on 4132 samples, validate on 2036 samples
Epoch 1/70
4132/4132 [==============================] - 3s 617us/step - loss: 0.6537 - accuracy: 0.6781 - val_loss: 0.5517 - val_accuracy: 0.7873
Epoch 2/70
4132/4132 [==============================] - 1s 234us/step - loss: 0.5274 - accuracy: 0.7965 - val_loss: 0.5255 - val_accuracy: 0.7873
Epoch 3/70
4132/4132 [==============================] - 1s 234us/step - loss: 0.5088 - accuracy: 0.7965 - val_loss: 0.5142 - val_accuracy: 0.7873
Epoch 4/70
4132/4132 [==============================] - 1s 340us/step - loss: 0.4983 - accuracy: 0.7965 - val_loss: 0.5065 - val_accuracy: 0.7873
Epoch 5/70
4132/4132 [==============================] - 1s 245us/step - loss: 0.4905 - accuracy: 0.7965 - val_loss: 0.4994 - val_accuracy: 0.7873
Epoch 6/70
4132/4132 [==============================] - 1s 245us/step - loss: 0.4827 - accuracy: 0.7967 - val_loss: 0.4921 - val_accuracy: 0.7878
Epoch 7/70
4132/4132 [==============================] - 1s 245us/step - loss

In [90]:
y_pred=cl.predict(x_test)

In [105]:
y_pred

array([[0.11149198],
       [0.0273287 ],
       [0.8390083 ],
       ...,
       [0.2630846 ],
       [0.00422772],
       [0.1141961 ]], dtype=float32)

In [93]:
yy_pred=y_pred.copy()

In [95]:
yy_pred=(yy_pred>0.5)

In [104]:
yy_pred

array([[False],
       [False],
       [ True],
       ...,
       [False],
       [False],
       [False]])

In [100]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,yy_pred)

In [101]:
cm

array([[1170,   58],
       [ 174,  141]], dtype=int64)